### ISSUE TITLE
How do you set ContainerOptions in DotNetCore 3.X?

### ISSUE THREAD

**Issue by randygeyer** [seesharper/LightInject.Microsoft.Hosting#13]
Hi,

I don't see a way to set ContainerOptions when using the IHostBuilder.UseLightInject() extension.  You currently have them hard-coded in the IHostBuilder.UseLightInject() extension.  What am I missing?  

Could you expose an Action<ContainerOptions> or Func<ContainerOptions> parameter in the UseLightInjection method?  I prefer Action so you could set some default options and allow us to add additional (e.g. EnablePropertyInjection = false, or enable logging).

Forgive me if I've missed something obvious.

Thanks - rg

**Comment by randygeyer** [comment]
I see you set EnablePropertyInjection to false by default.  What about enabling logging?

**Comment by seesharper** [comment]
Closes by #34
