### ISSUE TITLE
PerRequestLifeTime work incorrect

### ISSUE THREAD

**Issue by zayatsRB** [seesharper/LightInject.Microsoft.Hosting#16]
Hi
According integration https://www.lightinject.net/microsoft.aspnetcore.hosting/, I changed life time to PerRequestLifeTime in CompositionRoot. 
I was surprised when I saw that instance of service is created every time. 

I have used LightIinject.Annotation for injection property in controllers and DBContext has been created in each services of controller.

**Comment by seesharper** [comment]
Hi.

PerRequest means a new instance every time the service is requested from the controller. 

What you want here is `PerScope` which in a web application means "per web request" since a scope is started for each web request
